import {
  Avatar,
  Box,
  Flex,
  Modal,
  ModalContent,
  ModalOverlay,
  ModalHeader,
  Button,
  ModalCloseButton,
  ModalBody,
  ModalFooter,
  Spacer,
  Text,
  useDisclosure,
  Divider,
  Icon
}
  from '@chakra-ui/react'
import { SettingsIcon } from "@chakra-ui/icons"
import { supabase } from '../supabaseClient'
import color from "../etc/colors"
import Head from 'next/head'
import { useEffect } from 'react'
import { FaGoogle, FaDiscord, FaGithub } from 'react-icons/fa'

export default function Home() {
  useEffect(() => {
    if(supabase.auth.user() === null) {
      onLoginOpen()
    }
    console.log(supabase.auth.user())
  }, [])
  const { isOpen, onOpen, onClose } = useDisclosure()
  const { isOpen:isLoginOpen, onOpen:onLoginOpen, onClose:onLoginClose } = useDisclosure({ defaultIsOpen: true})
  return (
    <div>
      <Head>
        <title>Caffe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Flex sx={{filter: isLoginOpen? "blur(5px)": "none"}} flexDirection={"row"} height="100vh">
          <Box bg={color.subBase} flexGrow={1}>
            <Flex flexDirection={"row"} margin="30px 15px" alignItems="center">
              <Avatar src="/profile.jpg" borderRadius={"15px"} />
              <Box marginLeft={3}>
                <Text color={color.rosewater}>Rin Valentine</Text>
                <Text color={color.subtext}>Online</Text>
              </Box>
              <Spacer />
              <SettingsIcon w={5} h={5} marginRight={"1vw"} cursor="pointer" color="#AAAAAA" onClick={onOpen} />
            </Flex>
          </Box>
          <Box bg={color.base} flexGrow={19}>

          </Box>
        </Flex>

        {/* Settings Modal */}
        <Modal isOpen={isOpen} onClose={onClose}>
          <ModalOverlay />
          <ModalContent bg={color.subBase} color={"#aaa"}>
            <ModalHeader>Settings</ModalHeader>
            <ModalCloseButton />
            <ModalBody>
              <Text>
                asdlkamsdlkamsldkamsdlkasmdlak
              </Text>
            </ModalBody>
            <ModalFooter>
              <Button colorScheme='mochaPink' variant="solid" mr={3} onClick={onClose}>
                Save
              </Button>
            </ModalFooter>
          </ModalContent>
        </Modal>
        {/* Login Modal */}
        <Modal closeOnOverlayClick={false} isOpen={isLoginOpen} onClose={onLoginClose}>
          <ModalOverlay />
          <ModalContent w={300} bg={color.subBase} color={"#aaa"}>
            <ModalHeader textAlign={"center"}>Login</ModalHeader>
            <Divider/>
            <ModalBody display={"flex"} 
                       flexDirection={"column"}
                       justifyContent={"center"}
                       alignItems={"center"}
                       marginRight="none">
              
              <Button leftIcon={<Icon as={FaGoogle} />} colorScheme={"mochaPink"} variant="solid" mt={5}>
                Login with Google
              </Button>
              <Button leftIcon={<Icon as={FaDiscord} />} colorScheme={"mochaTeal"} variant="solid" mt={3}>
                Login with Discord
              </Button>
              <Button leftIcon={<Icon as={FaGithub} />} colorScheme={"mochaTeal"} variant="outline" mt={3} mb={10}>
                Login with Github
              </Button>
            </ModalBody>
          </ModalContent>
        </Modal>
      </main>
    </div>
  )
}
